create table if not exists public.offers (
 id bigint generated by default as identity primary key,
 name text not null,
 description text,
 price numeric(10,2) not null default 0,
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists public.bookings (
 id bigint generated by default as identity primary key,
 booking_code text unique not null,
 customer_name text not null,
 phone text not null,
 visit_date date not null,
 people_count integer not null check (people_count > 0 and people_count <= 100),
 offer text,
 status text not null default 'new' check (status in ('new','confirmed','completed','cancelled')),
 created_at timestamptz not null default now()
);
create index if not exists bookings_visit_date_idx on public.bookings(visit_date);
create index if not exists bookings_status_idx on public.bookings(status);
insert into public.offers(name,description,price) values
('50تذكرة المرح','دخول + ألعاب مختارة لمدة ساعتين',),
('باقة العائلة','4 أشخاص + ألعاب مختارة + مشروب لكل شخص',149),
('حفلة الأصدقاء','حتى 8 أشخاص + مساحة احتفال + أنشطة خاصة',299)
on conflict do nothing;
alter table public.offers enable row level security;
alter table public.bookings enable row level security;
create policy "public read active offers" on public.offers for select using (active = true);
